services:
  db:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keyshade_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - keyshade-dev
  redis:
    image: redis:6
    ports:
      - '6379:6379'
    networks:
      - keyshade-dev
    volumes:
      - ./data/redis:/data
networks:
  keyshade-dev:
    driver: bridge
